from django.conf.urls.defaults import *

urlpatterns = patterns('campusdeal.views',
    (r'^$', 'index'),
    (r'^register/$', 'register'),
    (r'^home/$', 'home'),
    (r'^search/$', 'search'),
    (r'^reg_submit/$', 'reg_submit'),
    (r'^item/(?P<item_id>\d+)/$', 'item'),
    (r'^remove_bid/(?P<bid_id>\d+)/$', 'remove_bid'),
    (r'^bids/$', 'bids'),
    (r'^accept_bid/$', 'accept_bid'),
    (r'^add_item/$', 'add_item'),
    (r'^item_added/$', 'item_added'),
    (r'^updateBidder/(?P<item_id>\d+)/$', 'updateBidder'),
    (r'^myitems/$', 'myitems'),
    (r'^next_recent/$', 'next_recent'),
    (r'^previous_recent/$', 'previous_recent'),
    (r'^myitems/static$', 'myitems_static'),
    (r'^mybids/$', 'mybids'),
    (r'^logout/$', 'logout'),
    (r'^all/$', 'all'),
    (r'^cycles/$', 'cycles'),
    (r'^electronics/$', 'electronics'),
    (r'^coolers/$', 'coolers'),
    (r'^books/$', 'books'),
    (r'^tickets/$', 'tickets'),
    (r'^others/$', 'others'),
    (r'^user_info/$', 'user_info'),
)
